### PR TITLE
Resolve #168

### LINKED ISSUE #168: HtmlEditorExtender InsertImage error in IIS
I am facing identical errors to #43. The control works fine in IIS Express but when hosted locally in IIS an error is produced when clicking Upload. It is the same error shown in several other posts - like 43 above.

I'm using AjaxControlToolkit v16.1 in an asp.net v4.6.1 project. Setting the trust level to Full doesn't help. UseAbsoluteHandlerPath is not available as a control attribute. I can see the value being set in the js debug file, but not in the release version. Adding the IIS app name to the AjaxFileUploadHandler.axd path in web.config also doesn't help.

The console error is: the server cannot find the requested URI: http://localhost/AjaxFileUploadHandler.axd?.. It is interesting that this is the same error even after changing the path in web.config, suggesting that UseAbsoluteHandlerPath is set to true in release. Maybe the problem is that I simply don't know how to set that flag, apart from overwriting it in AjaxFileUpload.debug.js, which causes the build to fail.

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**
Set upload handler path at server side and expose it to HtmlEditorExtender InsertImage button.

### CODE REVIEW

File: AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs [hunk 1]
```diff
@@ -118,6 +118,7 @@ public AjaxFileUpload()
         /// <summary>
         /// Whether or not to use absolute path for AjaxFileUploadHandler
         /// </summary>
+        [Obsolete]
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs]: I'd add a message "Use ... instead"

**Comment by AlekseyMartynov** [comment]
:shipit:
