### PR TITLE
Detect the AjaxFileUploadHandler path for nested applications automatically (Resolve #231)

### LINKED ISSUE #231: AjaxFileUploadHandler.axd not found in subsite
### The installation method
- [X] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Create subsite of Default Web Site in IIS
Add ajaxfileupload control to a usercontrol on a page in the subsite

### Actual result
The AjaxFileUploadHandler.axd will be search in the root site, and it won't be found there, because it lives in the subsite.
Logging from IIS:
... POST /AjaxFileUploadHandler.axd contextKey=.... 404 0 2 8

### Expected result
The AjaxFileUploadHandler.axd should be found at the level where is has been added.

### Browser(s) used
Internet Explorer 11

### A site deployment method
- [ ] VS development web-server,
- [X] IIS

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**

### CODE REVIEW

File: AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs [hunk 1]
```diff
@@ -485,8 +483,23 @@ public bool AutoStartUpload
...
+        string ResolveUploadHandlerPath(string uploadHandlerPath) {
+            if(String.IsNullOrWhiteSpace(uploadHandlerPath))
+                return CombineUrl(Page.Request.ApplicationPath, "AjaxFileUploadHandler.axd");
+
+            return uploadHandlerPath;
         }
 
+        string CombineUrl(string part1, string part2) {
+            if(!part1.EndsWith("/"))
+                part1 = part1 + "/";
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs]: part1 += "/"

File: AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs [hunk 2]
```diff
@@ -485,8 +483,23 @@ public bool AutoStartUpload
...
+        }
+
+        string ResolveUploadHandlerPath(string uploadHandlerPath) {
+            if(String.IsNullOrWhiteSpace(uploadHandlerPath))
+                return CombineUrl(Page.Request.ApplicationPath, "AjaxFileUploadHandler.axd");
+
+            return uploadHandlerPath;
         }
 
+        string CombineUrl(string part1, string part2) {
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs]: can be made static

**Comment by AlekseyMartynov** [comment]
LGTM
