### PR TITLE
Fix the nested ModalPopup scrolling (Resolve #257)

### LINKED ISSUE #257: The nested ModalPopup is located outside the viewport when scrolling the document window
Hello,
draggable ModalPopup doesn't work correctly when it is nested. See the file linked at the end. If a document is bigger than the viewport, scrolling the document makes the inner popup drift out of the view. If PopupDragHandleControlID attribute is removed then it behaves correctly, but users can't check what's behind the inner popup.
I'm sure it doesn't work with 16.x branch but older ones likely had the same issue.

https://gist.github.com/0bo0/897dcf87f21f64cfbc196401e46d0480

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**
We do not call `_onLayout()` method for a non-current ModalPopup to avoid scrolling of multiple elements when a popup is shown.

### CODE REVIEW

File: AjaxControlToolkit/Scripts/ModalPopup.js [hunk 1]
```diff
@@ -198,43 +198,20 @@ Sys.Extended.UI.ModalPopupBehavior.prototype = {
...
-                topZIndex = backgrounds[i].style.zIndex;
-
-            if(backgrounds[i].style.zIndex > topZIndex) {
-                topZIndex = backgrounds[i].style.zIndex;
-            }
-        }
-
-        return topZIndex;
+    _getLastPopup: function () {
+        return Sys.Extended.UI.ModalPopupBehavior.popups.length
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/Scripts/ModalPopup.js]: I'd captured `Sys.Extended.UI.ModalPopupBehavior.popups.length` into a var.
