### PR TITLE
Parsing of dates earlier than 100 is fixed in IE (Resolve #299)

### LINKED ISSUE #299: Calendar does not handle some years gracefully
### The AJAX Control Toolkit \<VERSION\>

16.1.1

### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug

1. In IE11, navigate to your demo site: https://ajaxcontroltoolkit.devexpress.com/Calendar/Calendar.aspx
2. Enter a year of 1/1/0001 into the third example (with the calendar button)
3. Click the calendar button to open the dropdown calendar

### Actual result

Calendar is filled with NaN in each cell

### Expected result

Chrome's behavior of using 1901 is reasonable.

### Browser(s) used

IE11 (maybe other IE flavors)

### A site deployment method
- [ ] VS development web-server,
- [x] IIS

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**

### CODE REVIEW

File: AjaxControlToolkit/Scripts/Calendar.js [hunk 1]
```diff
@@ -1547,6 +1547,8 @@ Sys.Extended.UI.CalendarBehavior.prototype = {
         var value = null;
         if(text) {
             value = Date.parseLocale(text, this.get_format());
+            if(value.getYear() < 100)
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/Scripts/Calendar.js]: getFullYear?
