### PR TITLE
Fix double raising Rating's Changed event (Resolve #379)

### LINKED ISSUE #379: AjaxControlToolkit Rating_Changed event fires twice
### The AJAX Control Toolkit \<VERSION\>
AjaxControlToolkit v 17.1.1
### The installation method
- [ ] Installer
- [ x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Rating control clicked resulted in Rating_Changed event fired twice
### Actual result
Rating count is indeed incremented twice in database
### Expected result
Rating count should only be incremented by one in database
### Browser(s) used
All major browsers tried with same result, Chrome, Firefox, IE, Opera
### A site deployment method
- [ x] VS development web-server,
- [ ] IIS

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**

### CODE REVIEW

**Comment by MikhailTymchukDX** [comment]
This method [is always called in the `_onStarClick` method](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/Rating.js#L95), which, in turn, triggers the `set_rating` method.
Server code is responsible for firing both the `OnClick` and `OnChanged` events, so an extra `doCallback()` call is not needed.

**Comment by AlekseyMartynov** [comment]
What if `set_rating` is called from a user code?

**Comment by MikhailTymchukDX** [comment]
Then the server will not know about it.
Maybe change it like this?
```js
set_rating: function(value) {
    if(this._ratingValue != value) {
        this._ratingValue = value;
        this._currentRating = value;

        if(this.get_isInitialized()) {
            if((value < 0) || (value > this._maxRatingValue))
                return;

            this._update();

            Sys.Extended.UI.RatingBehavior.callBaseMethod(this, 'set_ClientState', [this._ratingValue]);

            this.raisePropertyChanged('rating');
            this.raise_rated(this._currentRating);
        }
    }
    doCallback();
},


_onStarClick: function(e) {
    if(this._readOnly)
        return;

    this.set_rating(this._currentRating);
},
```

**Comment by AlekseyMartynov** [comment]
It's interesting that `_onStarClick` was sending callbacks unconditionally but `set_rating` - only when there was a change. We need to dig deeper into the code.

File: AjaxControlToolkit/Rating/Rating.cs [hunk 1]
```diff
@@ -401,13 +395,25 @@ public class Rating : Panel, ICallbackEventHandler, IPostBackEventHandler {
...
-            var args = new RatingEventArgs(eventArgument);
+            HandleEvent(eventArgument);
+        }
+
+        private RatingEventArgs HandleEvent(string eventArgument) {
+            var eventArgumentParts = eventArgument.Split(';');
+            var eventName = eventArgumentParts[0];
 
-            OnClick(args);
+            var args = new RatingEventArgs(eventArgumentParts[1] + ";" + eventArgumentParts[2]);
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/Rating/Rating.cs]: Since we already do split, we can change the `RatingEventArgs` to accept 2 arguments

File: AjaxControlToolkit/Rating/Rating.cs [hunk 2]
```diff
@@ -401,13 +395,25 @@ public class Rating : Panel, ICallbackEventHandler, IPostBackEventHandler {
...
+
+            if(eventName == "click")
+                OnClick(args);
+
+            if(eventName == "rating") {
+                var value = Convert.ToInt32(args.Value.Replace(";", ""));
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/Rating/Rating.cs]: is `Replace` still needed?

**Comment by AlekseyMartynov** [comment]
(See also my concerns in the chat)
