### PR TITLE
A sender of AjaxFileUpload events is fixed (Resolve #327)

### LINKED ISSUE #327: AjaxFileUpload events have an invalid sender
### The installation method
- [ ] Installer
- [# ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Setting up the extender as normal way

### Actual result
Failed at ImageUploadComplete as the sender is now a AjaxFileUpload.UploadRequestProcessor instead of AjaxFileUpload. Thus I'm not able to cast it and do the SaveAs as before. 

### Expected result
The ImageUploadComplete sender was previously a AjaxFileUpload which I can cast and do SaveAs.

### Browser(s) used
IE

### A site deployment method
- [ #] VS development web-server,
- [ ] IIS

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**

### CODE REVIEW

File: AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs [hunk 1]
```diff
@@ -252,6 +252,7 @@ public bool AutoStartUpload
                 return;
                 
             var processor = new UploadRequestProcessor {
+                Control = this,
                 Context = Context,
```
Comment (AlekseyMartynov) [inline AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs]: Since we now have a reference to the control, please check if we can remove the `Context` field.

```c#
if(control.Page != null)
    return control.Page.Request.RequestContext.HttpContext
```
